(function(){'use strict';const API_URL='/webman/3rdparty/IDNNOVLogAgent/api.cgi',q=id=>document.getElementById(id);
// DSM web server requires the CSRF token on every request to package CGIs
// (403 HTML otherwise). The token lives in the DSM desktop session object;
// when the app runs inside the desktop iframe it is reachable via parent/top.
function dsmToken(){const cands=[window,parent,top];for(const w of cands){try{const t=w&&w.SYNO&&w.SYNO.SDS&&w.SYNO.SDS.Session&&w.SYNO.SDS.Session.SynoToken;if(t)return t}catch(_){}}return null}
async function call(action,params={}){const u=new URL(API_URL,location.origin);u.searchParams.set('action',action);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const headers={};const t=dsmToken();if(t)headers['X-SYNO-TOKEN']=t;const response=await fetch(u,{method:'GET',headers,credentials:'same-origin'});let body=null;try{body=await response.json()}catch(_){if(response.status===403)throw new Error('HTTP 403 — session DSM expirée? Fermez et rouvrez l\'application.')}if(!response.ok||!body.success)throw new Error(body.code||('HTTP '+response.status));return body.data}
function settings(){return{collector_url:q('collector').value,organization:q('organization').value,company_name:q('company').value,stream:q('stream').value,nas_name:q('nas').value,device_id:q('device').value,ingest_user:q('ingest-user').value}}
async function load(){try{const s=await call('get_settings');q('collector').value=s.collector_url;q('organization').value=s.organization;q('company').value=s.company_name;q('stream').value=s.stream;q('nas').value=s.nas_name;q('device').value=s.device_id;q('ingest-user').value=s.ingest_user;q('password').placeholder=s.ingest_password_configured?'Configuré — laisser vide pour conserver':'Non configuré';const st=await call('get_status');q('status').querySelector('dd').textContent=st.running?'En fonctionnement':'Arrêté';q('destination').textContent=`${st.organization}/${st.stream} — ${st.nas_name}`}catch(e){q('result').textContent='Accès refusé ou service indisponible.'}}
// Auto-test à l'ouverture : la ligne "Connexion OpenObserve" affiche le code HTTP réel (200 OK attendu).
async function autoTest(){const c=q('conn');try{const s=settings(),r=await call('test_connection',{collector_url:s.collector_url,organization:s.organization,stream:s.stream,ingest_user:s.ingest_user});if(r.success){c.textContent=`Connexion réussie — HTTP ${r.http_status||200} OK`;c.style.color='#1a7f37'}else{c.textContent=`Échec — ${r.code}`;c.style.color='#b42318'}}catch(e){c.textContent='Test indisponible — '+e.message;c.style.color='#b42318'}}
q('test').onclick=async()=>{try{const s=settings(),r=await call('test_connection',{collector_url:s.collector_url,organization:s.organization,stream:s.stream,ingest_user:s.ingest_user});q('result').textContent=r.success?`Connexion réussie — HTTP ${r.http_status||200} OK`:`Échec — ${r.code}`}catch(e){q('result').textContent=e.message}};
q('apply').onclick=async()=>{const p=q('password').value.trim();try{const{nonce}=await call('nonce');const params={settings:JSON.stringify(settings()),password_action:p?'replace':'preserve'};if(p){const masked=btoa([...p].map((c,i)=>String.fromCharCode(c.charCodeAt(0)^nonce.charCodeAt(i%nonce.length))).join(''));params.password=masked;params.nonce=nonce}await call('save_settings',params);q('password').value='';q('result').textContent='Configuration appliquée.';await load();autoTest()}catch(e){q('result').textContent=e.message}};
load();autoTest();setInterval(load,20000)})();
