#!/bin/sh
set -eu
test -f "${SYNOPKG_PKGVAR:?}/etc/settings.json"
if test -f "$SYNOPKG_PKGVAR/etc/token"; then chmod 0600 "$SYNOPKG_PKGVAR/etc/token"; fi
export PYTHONPATH="${SYNOPKG_PKGDEST:?}/lib"
"${SYNOPKG_PKGDEST:?}/bin/py" -m idnnov_agent.bootstrap
